[package]
name = "ckb-vm-definitions"
version = "0.12.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
autobins = false

[[bin]]
name = "generate_asm_constants"
path = "src/generate_asm_constants.rs"
